const text = {
  appName: 'My iTunes',
  musicHeadline: 'iTunes Music',
  favoritesHeadline: 'Favorites',
  modalApply: 'Apply',
  modalCancel: 'Cancel',
  modalAdd: 'Add',
  modalSave: 'Save',
  buttonDelete: 'Delete',
  buttonChange: 'Change',
  buttonSearch: 'Search',
  buttonSignIn: 'Sign In',
  buttonCancel: 'Cancel',
  buttonPlaySong: 'Play preview of song',
  placeholderForGenderSelect: 'Select a gender',
  placeholderForSearchMusic: 'Enter artist',
  placeholderForUserInput: 'Enter your name',
  placeholderForEmailInput: 'Enter your email',
  placeholderForPasswordInput: 'Enter your password',
  genderMale: 'male',
  genderFemale: 'female',
  imgAlt: 'Artist',
  xTitle: 'Artist',
  queriesTitle: 'Count of search queries',
  playingTitle: 'Count of playing',
  closeFavorites: 'Go to my Favorites',
  openFavorites: 'My Favorites',
  searchAnalytics: 'Search Analytics',
  playAnalytics: 'Play Analytics',
  errorRequired: 'This field is required!',
  errorEmail: 'Invalid email address!',
  errorPassword: 'The password must be allowed at least 8 characters long.'
};

export default text;
